# Generated by Django 5.0.3 on 2024-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restourant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('years_of_experience', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(to='Restourant.cooker'),
        ),
        migrations.DeleteModel(
            name='Cook',
        ),
        migrations.DeleteModel(
            name='DishIngredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
