# Generated by Django 5.0.3 on 2024-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restourant', '0003_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rules',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
